{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tibiadata-api-go.fullname" . }}
  labels:
    {{- include "tibiadata-api-go.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.settings }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}