name: bump-helm-chart

on:
  repository_dispatch:
    types:
      - bump-helm-chart-release

jobs:
  bump:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get current version
        id: get_version
        run: |
          echo "version=$(yq eval '.version' charts/${{ github.event.client_payload.chart_name }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Increment Semantic Version
        uses: christian-draeger/increment-semantic-version@1.2.3
        id: bump_version
        with:
          current-version: ${{ steps.get_version.outputs.version }}
          version-fragment: patch

      - name: Update Chart versions
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          branch: "bump/${{ github.event.client_payload.chart_name }}/${{ github.event.client_payload.release_version }}"
          targetBranch: ${{ github.event.repository.default_branch }}
          masterBranchName: ${{ github.event.repository.default_branch }}
          createPR: "true"
          labels: automated,bump
          title: "bump: ${{ github.event.client_payload.chart_name }} release ${{ github.event.client_payload.release_version }}"
          message: "bump: ${{ github.event.client_payload.chart_name }} release ${{ github.event.client_payload.release_version }}"
          description: |
            The Helm chart for [${{ github.event.client_payload.chart_name }}](${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.client_payload.chart_name }}) was updated due to release [v${{ github.event.client_payload.release_version }}](${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.client_payload.chart_name }}/releases/tag/v${{ github.event.client_payload.release_version }}).

            ```yaml
            appVersion: ${{ github.event.client_payload.release_version }}
            version: ${{ steps.bump_version.outputs.next-version }}
            ```

            _This PR is automated by [${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.event.repository.default_branch }}/.github/workflows/bump.yaml) workflow._
          changes: |
            {
              "charts/${{ github.event.client_payload.chart_name }}/Chart.yaml": {
                "version": "${{ steps.bump_version.outputs.next-version }}",
                "appVersion": "${{ github.event.client_payload.release_version }}"
              }
            }
