name: release-helm-chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  release:
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      packages: write # needed for ghcr access
      id-token: write # needed for keyless signing

    runs-on: ubuntu-latest
    outputs:
      changed_charts: ${{ steps.chart_releaser.outputs.changed_charts }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 #v4.3.1
        with:
          version: latest

      - name: Run chart-releaser
        id: chart_releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f #v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true

      # see https://github.com/helm/chart-releaser/issues/183
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 #v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push charts to GHCR
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/tibiadata/charts"
          done

  argocd:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Get Helm Chart versions
        id: get_chart_versions
        uses: jacobtomlinson/gha-read-helm-chart@ca2f3b5038208efd3279dbe941e448d7ccdccbf6 #0.1.3
        with:
          path: ${{ needs.release.outputs.changed_charts }}

      - name: Trigger workflow in tibiadata-argocd-app-of-apps repo
        uses: peter-evans/repository-dispatch@5fc4efd1a4797ddb68ffd0714a238564e4cc0e6f #v4.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: tibiadata/tibiadata-argocd-app-of-apps
          event-type: bump-tibiadata-helm-chart-versions
          client-payload: '{"chart_name": "${{ steps.get_chart_versions.outputs.name }}", "chart_version": "${{ steps.get_chart_versions.outputs.version }}"}'
